name: Ungoogled-chromium-android build dispatch
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+.[0-9]+-[0-9]+'

jobs:
  build:
    name: Send workflow dispatch to runner repo
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Send build request
        env:
          PAT_USERNAME: ${{ secrets.PAT_USERNAME }}
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
          REPO_NAME: ${{ secrets.REPO_NAME }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          .github/workflows/dispatch-request.sh