name: Ungoogled-chromium-android build test
on: [push, pull_request, repository_dispatch]

jobs:
  build:
    name: Build Chromium
    runs-on: ubuntu-18.04
    container: archlinux:latest

    steps:
      - uses: actions/checkout@v1
        name: Clone repository
        with:
          submodules: true
      - name: Install dependencies
        run: |
          pacman -Sy --noconfirm
          pacman -S --noconfirm gnu-free-fonts wget
          pacman -S --noconfirm --needed base base-devel nss alsa-lib xdg-utils libxss libcups libgcrypt libpulse pciutils json-glib libva jsoncpp python python2 pyenv gperf wget yasm mesa ninja git clang lld gn llvm quilt
      - name: Install python environment
        run: |
          wget "https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh"
          echo "bfe34e1fa28d6d75a7ad05fd02fa5472275673d5f5621b77380898dee1be15d2 Miniconda3-latest-Linux-x86_64.sh" | sha256sum --check --status
          chmod +x Miniconda3-latest-Linux-x86_64.sh && ./Miniconda3-latest-Linux-x86_64.sh -b -p ~/anaconda
          source ~/anaconda/bin/activate
          conda init
          conda create -y --name py2 python=2
          conda activate py2
      - name: Build
        run: |
          ./build.sh
      - name: Move artifact
        run: |
          pwd
          ls -la
